/**
 * Created by tgulati on 2/28/17.
 */
public class AddedCharacter {

    /**
     * Given two strings s and t which consist of only lowercase letters.

     String t is generated by random shuffling string s and then add one more letter at a random position.

     Find the letter that was added in t.

     Example:

     Input:
     s = "abcd"
     t = "abcde"

     Output:
     e

     Explanation:
     'e' is the letter that was added.
     * @param s
     * @param t
     * @return
     */

    public char findTheDifference(String s, String t) {
        int asciiCodeSum = t.charAt(s.length());
        // iterate through both strings, calculate the ascii sum
        for (int i = 0; i < s.length(); ++i) {
            asciiCodeSum -= (int) s.charAt(i);
            asciiCodeSum += (int) t.charAt(i);
        }
        return (char) asciiCodeSum;
    }
}
